# https://starship.rs/config/

# Don't print a new line at the start of the prompt
add_newline = false

[package]
symbol = "âœ"
disabled = true

[animation]
disabled = false
frames = ["ğŸ¶ğŸ·ğŸ›", "ğŸµğŸ·ğŸ›"]
interval = 1
